on:
  # schedule:
    # used to run every 15 minutes starting from minute 0 of every hour in jan, feb, sep-dec
    # - cron:  '15 9 * 1,2,9-12 2'
  workflow_dispatch:

name: Update Schedule Data

jobs:
  render:
    name: Update Schedules
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies from DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            dplyr
            lubridate
            glue
            magrittr
            callr
      - name: Run update script
        run: Rscript -e 'source("R/update_sched.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'source("R/make_sched_commit.R")'
          git push origin master || echo "No changes to commit"
